version : '2'
services:
    postgres:
        image:  postgres:latest
        environment: 
            POSTGRES_USER: test2
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test2
            PGPORT: 6543
        ports:
            - "6543:6543"
        volumes:
            - postgres-data:/test
volumes:
    postgres-data: